### ISSUE TITLE
Are non-Opera people empowered as Committers/Maintainers?

### ISSUE THREAD

**Issue by RobDolinMS** [pwarocks/pwa.rocks#143]
Per this tweet (https://twitter.com/marcosc/status/803925701954932736) from @MarcosCaceres, it looks like a number of top contributors maintainers of this project were let go.  :(

Are there non-Opera people who are committers / maintainers?

Will this effort be able to continue?

**Comment by C-F-4** [comment]
I didn't know that. That's why this project has been inactive.
Well, I'm just a committer. Not a Maintainer. But yeah, there are a couple of other committers whose apps it is, or who just like the project. Well, those guys were the maintainers.  @RobDolinMS

**Comment by andreasbovens** [comment]
We're still maintaining this project — in fact, that's why we moved out of the Opera org (still working on domain name transfer). Happy to get other people on board as committers/maintainers, of course.

And yes, we're aware there is a bit of a backlog. We're working our way through that :)

**Comment by C-F-4** [comment]
It's great to know that the project is still up. @andreasbovens

**Comment by C-F-4** [comment]
Is the project being moderated? How long before the Project(PR and Issues) are active? @andreasbovens

**Comment by andreasbovens** [comment]
I've started working my way through the various PRs, integrating them one by one. Sorry for the delay - life has been busy the last couple of weeks.
