### ISSUE TITLE
Airhorner

### ISSUE THREAD

**Issue by jebeld17** [pwarocks/pwa.rocks#176]
airhorner.com

**Comment by dandv** [comment]
![image](https://cloud.githubusercontent.com/assets/33569/25251766/4774a84a-25cf-11e7-9603-d44cb3981029.png)

@abraham, please close

**Comment by abraham** [comment]
I don't have the ability to manage issues.

**Comment by shwetank** [comment]
Well, closing since airhorner is already featured.
